development:
  adapter: postgresql
  encoding: unicode
  database: meurio_development
  pool: 5
  username: meurio
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: meurio_test
  pool: 5
  username: meurio
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: meurio_production
  pool: 5
  username: meurio
  password:
