development:
  adapter: postgresql
  encoding: unicode
  database: meurio_development
  pool: 5
  username: meurio
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: meurio_test
  pool: 5
  username: meurio
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: meurio_production
  pool: 5
  username: meurio
  password:

accounts_development:
  adapter: postgresql
  encoding: unicode
  database: meurio_accounts_development
  pool: 5
  username: meurio
  password:

accounts_test:
  adapter: postgresql
  encoding: unicode
  database: meurio_accounts_test
  pool: 5
  username: meurio
  password:

accounts_production:
  adapter: postgresql
  encoding: unicode
  database: meurio_accounts_production
  pool: 5
  username: meurio
  password:
